# from https://github.com/marketplace/actions/deploy-to-cloud-run
#********* needs to be edited!!! 


jobs:
  job_id:
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1.0.2

    - uses: 'actions/checkout@v3'

    - uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: 'hello-cloud-run'
        image: 'gcr.io/cloudrun/hello'

    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'




# name: hello world ci

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     # runs-on: ubuntu-latest
#     runs-on: ubuntu-lts

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.9

#     - name: Install dependencies
#       run: pip install -r requirements.txt

#     - name: Run tests
#       run: python manage.py test