# Modified from https://github.com/daneroo/phac-garden/blob/main/apps/site-nginx/cloudbuild.yaml
# https://cloud.google.com/artifact-registry/docs/configure-cloud-build
# steps:
#   # Build the container image 
#   - name: "gcr.io/cloud-builders/docker"
#     args: [
#         "build",
#         "-t",
#         # Fully qualified container registry image name
#         # "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}",
#         # docker context _root
#         # "apps/${_SERVICE_NAME}/.",
#         "northamerica-northeast1-docker.pkg.dev/phx-hellodjango/hello-world-app/djangoproject"
#         # "djangoproject/."
#       ]
#   # Push the container image to Container Registry #TODO - transition name to artifact registry
#   - name: "gcr.io/cloud-builders/docker"
#     args:
#       [
#         "push",
#         "northamerica-northeast1-docker.pkg.dev/phx-hellodjango/hello-world-app/djangoproject"
#         # "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}",
#       ]
#   # Deploy container image to Cloud Run
#   - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
#     entrypoint: gcloud
#     args:
#       - "run"
#       - "deploy"
#       - "${_SERVICE_NAME}"
#       - "--image"
#       - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}"
#       - "--region"
#       - "${_REGION}"
#       - "--allow-unauthenticated"

# substitutions:
#   # The must start with a "_" (_[A-Z0-9_]+)
#   _ARTIFACT_REGISTRY_REPO: "hello-world-app"
#   _SERVICE_NAME: "djangoproject"
#   _REGION: "northamerica-northeast1"
# images:
#   - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}"

# #cloudbuild.yaml from https://kevinsimper.medium.com/building-docker-images-with-docker-compose-on-google-cloud-container-builder-292b1eb3fd31
# steps:
# - name: 'docker/compose:1.19.0'
#   args: ['up', '-d']
# - name: 'gcr.io/cloud-builders/docker'
#   # args: ['tag', 'workspace_app:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
#   args: [ 'gcr.io/$PROJECT_ID/$REPO_NAME']
# images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']

steps:
  # Install dependencies
  - name: 'python:3.9'
    entrypoint: 'pip'
    args: ['install', '-r', 'djangoproject/requirements.txt']
# will need to change the path of this

  # Run tests
  - name: 'python:3.9'
    entrypoint: 'python'
    args: ['djangoproject/manage.py', 'test', 'hello_world']

  # # Build Docker image - this is old!
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', 'northamerica-northeast1-docker.pkg.dev/hello-world-app/web', '.']


  # # Push Docker image to Container Registry
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'northamerica-northeast1-docker.pkg.dev/hello-world-app/web']
    - name: 'gcr.io/cloud-builders/docker-compose'
      # args: ['build', '-t', 'northamerica-northeast1-docker.pkg.dev/hello-world-app/web', '.']
      args: ['build']

  # Step 2: Push the built images to a container registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push']
      # args: ['push' 'northamerica-northeast1-docker.pkg.dev/hello-world-app/web']

  # # Step 3: Deploy the Docker Compose project using the built images
  # - name: 'gcr.io/cloud-builders/docker-compose'
  #   args: ['-f', 'docker-compose.yaml', 'up', '-d']

  #   # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}"
      - "--region"
      - "${_REGION}"
      - "--allow-unauthenticated"

substitutions:
  # The must start with a "_" (_[A-Z0-9_]+)
  _ARTIFACT_REGISTRY_REPO: "hello-world-app"
  _SERVICE_NAME: "djangoproject"
  _REGION: "northamerica-northeast1"
images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}"