# For local use, use cloudbuild.yaml for pushing to artifact registry and deploying with cloud build
version: '1'
services:
  web:
    build: ./djangoproject
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - 8000:8000
    image: northamerica-northeast1-docker.pkg.dev/phx-hellodjango/hello-world-app/djangoproject
   
    ports:
      - 8000:8000
    volumes:
      - .:/hello_world

 
  # For running locally - remove image
  # TODO - add postgres/ alloydb

