# # Modified from https://github.com/daneroo/phac-garden/blob/main/apps/site-nginx/cloudbuild.yaml
# # https://cloud.google.com/artifact-registry/docs/configure-cloud-build
#  https://kevinsimper.medium.com/building-docker-images-with-docker-compose-on-google-cloud-container-builder-292b1eb3fd31

# This has 3 steps and set up in Cloud Build (console) to trigger on push to main branch

steps:

#   # Install dependencies
#   - name: 'python:3.9'
#     entrypoint: 'pip'
#     args: ['install', '-r', 'djangoproject/requirements.txt']
# # will need to change the path of this

#   # Run tests
#   - name: 'python:3.9'
#     entrypoint: 'python'
#     args: ['djangoproject/manage.py', 'test', 'hello_world']


# Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: [
        "build",
        "-t",
        # Artifact registry image name in form: HOST-NAME/PROJECT-ID/REPOSITORY/IMAGE
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}",
        # docker context _root  (where you'd find the Dockerfile in project to build/ push)
        "${_SERVICE_NAME}/.",
      ]
  # This is the same as:
  #  $ docker build  -t  northamerica-northeast1-docker.pkg.dev/pdcp-cloud-014-lilakelland/hello-world-app/hello-world djangoproject/.


# Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}",
      ]
  This is the ~ to:
  # $ docker push northamerica-northeast1-docker.pkg.dev/pdcp-cloud-014-lilakelland/hello-world-app/hello-world


# Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}"
      - "--region"
      - "${_REGION}"
      - "--allow-unauthenticated"
# Similar to:
#$ gcloud run deploy hello-world-app --image northamerica-northeast1-docker.pkg.dev/pdcp-cloud-014-lilakelland/hello-world-app/hello-world --region northamerica-northeast1 --allow-unauthenticated

substitutions:
  # The must start with a "_" (_[A-Z0-9_]+)
  # _ARTIFACT_REGISTRY_REPO: "hello-world-app"
  _ARTIFACT_REGISTRY_REPO: pdcp-cloud-014-lilakelland
  _SERVICE_NAME: "hello-world"
  _REGION: "northamerica-northeast1"
images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}"
